name:                yellow-stone
version:             0.0.1.0



default-extensions:
- NoImplicitPrelude


dependencies:
- base >= 4.7 && < 5
- aeson
- Hydra


library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -fhide-source-paths



executables:
  yellow-stone:
    main:                Main.hs
    source-dirs:         app/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-A32M
    - -with-rtsopts=-AL128
    - -with-rtsopts=-qn2
    - -Wall
    - -O2
    - -fspec-constr-recursive=10
    - -fno-ignore-asserts
